# Generated by Django 4.2.13 on 2024-07-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_profile_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
