# Generated by Django 4.2.13 on 2024-07-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="date_added",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(default="Canada", max_length=255),
        ),
    ]
