# Generated by Django 4.2.13 on 2024-07-12 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_remove_shippingaddress_date_added_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address1",
            new_name="shipping_address1",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address2",
            new_name="shipping_address2",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="email",
            new_name="shipping_email",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="full_name",
            new_name="shipping_full_name",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="state",
            new_name="shipping_state",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="zipcode",
            new_name="shipping_zipcode",
        ),
    ]
